version: '3.8'

services:
  meshquake:
    build: .
    volumes:
      - ./data:/app/data
    working_dir: /app
    environment:
      - DATA_DIR=/app/data
      - RADIO_IP=192.168.69.8
      - CH_INDEX=2
    command: >
      prod --zip 94040 --min-mag 2.5 --max-distance 300
      --radio-ip 192.168.69.8 --ch-index 2
    restart: unless-stopped
